### PR TITLE
Create animal table

### PR DESCRIPTION
**Pull request by AliRezaBmeDu**
In this branch I have done the following changes.

- Create a database named vet_clinic.
- Create a table named animals with the following columns:

          1.     id: integer
          2.     name: string
          3.     date_of_birth: date
          4.     escape_attempts: integer
          5.     neutered: boolean
          6.     weight_kg: decimal
 
- Insert four animals with attributes.
- Attach screenshots

name_ends-with_mon
DOB_between_16and19
neutered_and_esc_attempt
DOB_agumon_pikachu
weight10 5plus
neutered
not_gabumon
weight_between

### CODE REVIEW

**Review by Gambit142 — COMMENTED** [review]
Hi @AliRezaBmeDu 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- In the README file, kindly customize each section's header with information relevant to that section. Kindly remove all placeholder texts and the Live Demo section. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Ibizugbe — COMMENTED** [review]
Hi @AliRezaBmeDu 👋🏼👋🏼👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly remove every placeholder text on your readme file as this gives your project a less professional look. see the image below.
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Bantealem — COMMENTED** [review]
Hi @AliRezaBmeDu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has broken link in your readme file. Currently your `MIT` license is broken. Kindly fix it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Bantealem — APPROVED** [review]
# Status: Approved
Hi @AliRezaBmeDu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [x] Correct Git flow
- [x] Great Implementation of the project
- [x] Professional Readme
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
